[package]
name = "next_agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
next_contracts.workspace = true
next_mechanics.workspace = true

[dev-dependencies]
next_project.workspace = true

[lints]
workspace = true
