use xtask::report::{CommandReportV1, WaterLatticeDetailsV1};

pub(super) fn run() -> Result<(), String> {
    let report = next_verification::run_water_lattice_check().map_err(|error| error.to_string())?;
    CommandReportV1::emit(
        "water-lattice",
        "PASS",
        WaterLatticeDetailsV1 {
            check_id: "CONTINUUM-WATER-LATTICE-P1".to_owned(),
            region_id: report.region_id.to_hex(),
            cells: report.cells,
            edges: report.edges,
            run_ticks: report.run_ticks,
            total_volume_initial_mm3: report.total_volume_initial_cubic_millimetres.to_string(),
            total_volume_final_mm3: report.total_volume_final_cubic_millimetres.to_string(),
            conservation_exact: report.conservation_exact,
            east_column_wet_by_tick: report.east_column_wet_by_tick,
            settled_difference_max_um: report.settled_difference_max_micrometres,
            settle_tolerance_um: report.settle_tolerance_micrometres,
            levels_in_extent: report.levels_in_extent,
            dry_cells_final: report.dry_cells_final,
            final_level_east_um: report.final_level_east_micrometres,
            repeated_run_identical: report.repeated_run_identical,
            in_place_equals_cloning: report.in_place_equals_cloning,
            step_cost_cells: report.step_cost_cells,
            step_cost_edges: report.step_cost_edges,
            step_cost_max_us: report.step_cost_max_microseconds.to_string(),
            step_cost_mean_us: report.step_cost_mean_microseconds.to_string(),
            step_cost_debug_build: report.step_cost_debug_build,
            final_network_hash: report.final_network_hash.to_hex(),
            final_table_hash: report.final_table_hash.to_hex(),
            activity_run_identical: report.activity_run_identical,
            activity_wake_run_identical: report.activity_wake_run_identical,
            skipped_fraction_mean_permille: report.skipped_fraction_mean_permille,
            skipped_fraction_final_permille: report.skipped_fraction_final_permille,
            skipped_edges_final: report.skipped_edges_final,
            wake_tick: report.wake_tick,
            active_edges_after_wake: report.active_edges_after_wake,
            rest_cost_active_mean_us: report.rest_cost_active_mean_microseconds.to_string(),
            rest_cost_activity_mean_us: report.rest_cost_activity_mean_microseconds.to_string(),
            rest_probe_ticks: report.rest_probe_ticks,
            skipped_fraction_at_rest_probe_permille: report.skipped_fraction_at_rest_probe_permille,
            first_rest_tick_after_wet: report.first_rest_tick_after_wet,
            stage_records_match_active_edges: report.stage_records_match_active_edges,
            stage_records_max: report.stage_records_max,
            stage_fall_records_tick_30: report.stage_fall_records_tick_30,
            stage_droplets_tick_30: report.stage_droplets_tick_30,
            stage_fall_records_final: report.stage_fall_records_final,
            stage_droplets_final: report.stage_droplets_final,
            stage_pure: report.stage_pure,
            stage_bounds_ok: report.stage_bounds_ok,
            stage_cost_max_us: report.stage_cost_max_microseconds.to_string(),
            stage_cost_mean_us: report.stage_cost_mean_microseconds.to_string(),
        },
    )
}
