[package]
name = "next_game"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
desktop-sdl-ash = ["dep:next_desktop_sdl_ash", "dep:flate2", "dep:crc32fast"]
physical-sound-lab = ["next_application/physical-sound-lab"]
physical-sound-selected-glass = [
    "physical-sound-lab",
    "next_application/physical-sound-selected-glass",
]

[dependencies]
next_application.workspace = true
next_contracts.workspace = true
next_desktop_sdl_ash = { workspace = true, optional = true }
crc32fast = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
next_reference_game.workspace = true

[dev-dependencies]
next_assets.workspace = true
next_project.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
