[package]
name = "next_runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
physx = ["dep:next_physics_physx", "next_physics_physx/physx-sdk"]
physx-mock = ["dep:next_physics_physx", "next_physics_physx/mock-abi"]

[dependencies]
next_contracts.workspace = true
next_mechanics.workspace = true
next_physics_api.workspace = true
next_physics_physx = { workspace = true, optional = true }
next_rpg.workspace = true

[lints]
workspace = true
