#![forbid(unsafe_code)]

pub mod agent;
pub mod animation_content;
pub mod audio;
pub mod body;
pub mod canonical;
pub mod cognition;
pub mod command;
pub mod content;
pub mod extension;
pub mod identity;
pub mod ids;
pub mod input;
pub mod ledger;
pub mod localization;
mod manifest_jcs;
pub mod mechanics;
pub mod motor;
pub mod persistence;
pub mod physics;
pub mod platform;
pub mod preferences;
pub mod presentation;
pub mod project;
pub mod render_content;
pub mod rpg;
pub mod session;
pub mod snapshot;
pub mod targeting;
pub mod world;
pub mod world_activity;
pub mod world_population;
pub mod world_routine;
