#pragma once

#include <string>

namespace nextengine::nonlocal::fcr {

struct SplitBoundaryReport {
    bool passed = false;
    std::string json;
};

SplitBoundaryReport run_split_static_boundary_controls();
SplitBoundaryReport run_boundary_composition_smoke_controls();
SplitBoundaryReport run_boundary_reaction_accuracy_controls();
SplitBoundaryReport run_displacement_ownership_controls();
SplitBoundaryReport run_finite_precision_merit_controls();
SplitBoundaryReport run_floor_stationarity_trajectory_controls();
SplitBoundaryReport run_owned_gradient_controls();
SplitBoundaryReport run_owned_residual_trajectory_controls();
SplitBoundaryReport run_owned_boundary_composition_controls();
SplitBoundaryReport run_closed_box_eligibility_controls();
SplitBoundaryReport run_tiny_pressure_corpus_controls();
SplitBoundaryReport run_box_contact_kkt_controls();
SplitBoundaryReport run_box_contact_kkt_face_controls();
SplitBoundaryReport run_tiny_pressure_contact_kkt_controls();
SplitBoundaryReport run_contact_onset_forecast_controls();
SplitBoundaryReport run_tiny_pressure_contact_forecast_controls();
SplitBoundaryReport run_joint_neighborhood_controls();
SplitBoundaryReport run_joint_neighborhood_one_pass_controls();
SplitBoundaryReport run_joint_pressure_tape_controls();
SplitBoundaryReport run_joint_pressure_query_controls();
SplitBoundaryReport run_joint_pressure_controller_controls();
SplitBoundaryReport run_canonical_stage_controls();
SplitBoundaryReport run_balanced_canonical_controls();
SplitBoundaryReport run_balanced_stage_ledger_controls();
SplitBoundaryReport run_canonical_adaptive_controls();
SplitBoundaryReport run_canonical_adaptive_failure_probe_controls();
SplitBoundaryReport run_canonical_adaptive_ledger_probe_controls();
SplitBoundaryReport run_canonical_adaptive_p2_probe_controls();
SplitBoundaryReport run_canonical_adaptive_recovery_lanes_probe_controls();
SplitBoundaryReport run_canonical_adaptive_recovery_controls();
SplitBoundaryReport run_ledger_normalization_probe_controls();
SplitBoundaryReport run_ledger_normalization_controls();
SplitBoundaryReport run_kkt_scale_stage_ledger_probe_controls();
SplitBoundaryReport run_kkt_scale_stage_ledger_controls();
SplitBoundaryReport run_combined_adaptive_replay_probe_controls();
SplitBoundaryReport run_combined_adaptive_replay_controls();
SplitBoundaryReport run_fixed_canonical_reference_probe_controls();
SplitBoundaryReport run_fixed_canonical_reference_controls();
SplitBoundaryReport run_publication_cadence_probe_controls();
SplitBoundaryReport run_publication_cadence_controls();
SplitBoundaryReport run_publication_stability_probe_controls();
SplitBoundaryReport run_publication_stability_controls();
SplitBoundaryReport run_mixed_stability_budget_probe_controls();
SplitBoundaryReport run_mixed_stability_budget_controls();
SplitBoundaryReport run_macro_adaptive_transaction_probe_controls();
SplitBoundaryReport run_macro_adaptive_transaction_controls();
SplitBoundaryReport run_canonical_topology_probe_controls();
SplitBoundaryReport run_canonical_topology_controls();
SplitBoundaryReport run_macro_adaptive_replay_probe_controls();
SplitBoundaryReport run_macro_adaptive_replay_controls();
SplitBoundaryReport run_adaptive_fixed_diagnostic_probe_controls();
SplitBoundaryReport run_adaptive_fixed_diagnostic_controls();
SplitBoundaryReport run_adaptive_accuracy_budget_probe_controls();
SplitBoundaryReport run_adaptive_accuracy_budget_controls();
SplitBoundaryReport run_workspace_reuse_diagnostic_probe_controls();
SplitBoundaryReport run_workspace_reuse_diagnostic_controls();
SplitBoundaryReport run_retained_workspace_probe_controls();
SplitBoundaryReport run_retained_workspace_controls();
SplitBoundaryReport run_complete_retention_probe_controls();
SplitBoundaryReport run_complete_retention_controls();
SplitBoundaryReport run_static_support_index_probe_controls();
SplitBoundaryReport run_static_support_index_controls();
SplitBoundaryReport run_static_support_timing_controls();
SplitBoundaryReport run_complete_static_index_probe_controls();
SplitBoundaryReport run_complete_static_index_controls();
SplitBoundaryReport run_flat_adjacency_probe_controls();
SplitBoundaryReport run_flat_adjacency_controls();
SplitBoundaryReport run_flat_adjacency_timing_controls();
SplitBoundaryReport run_complete_flat_adjacency_probe_controls();
SplitBoundaryReport run_complete_flat_adjacency_controls();
SplitBoundaryReport run_nominal_alignment_preflight_controls();
SplitBoundaryReport run_nominal_hydro_spectrum_probe_controls();
SplitBoundaryReport run_nominal_hydro_macro_probe_controls();
SplitBoundaryReport run_nominal_hydro_query_evidence_ablation_controls();
SplitBoundaryReport run_nominal_hydro_topology_reuse_audit_controls();
SplitBoundaryReport run_nominal_hydro_cached_topology_ablation_controls();
SplitBoundaryReport run_nominal_hydro_hvp_coefficient_ablation_controls();
SplitBoundaryReport run_nominal_hydro_evaluation_tape_dataflow_audit_controls();
SplitBoundaryReport run_nominal_hydro_fused_evaluation_tape_ablation_controls();
SplitBoundaryReport run_nominal_hydro_fused_phase_timing_controls();
SplitBoundaryReport
run_nominal_hydro_owner_computes_dataflow_audit_controls();
SplitBoundaryReport
run_nominal_hydro_owner_parallel_controls(int worker_count);
SplitBoundaryReport
run_nominal_hydro_owner_parallel_phase_timing_controls();
SplitBoundaryReport
run_nominal_hydro_masked_superset_plan_audit_controls();
SplitBoundaryReport
run_nominal_hydro_masked_superset_plan_controls();
SplitBoundaryReport
run_nominal_hydro_partitioned_active_plan_audit_controls();
SplitBoundaryReport
run_nominal_hydro_partitioned_active_plan_controls();
SplitBoundaryReport
run_nominal_hydro_current_topology_plan_audit_controls();
SplitBoundaryReport
run_nominal_hydro_split_incoming_plan_audit_controls();
SplitBoundaryReport
run_nominal_hydro_incoming_construction_audit_controls();
SplitBoundaryReport
run_nominal_hydro_split_incoming_plan_controls();
SplitBoundaryReport
run_nominal_hydro_split_incoming_phase_timing_controls();
SplitBoundaryReport
run_nominal_hydro_directed_scratch_audit_controls();
SplitBoundaryReport
run_nominal_hydro_directed_scratch_reuse_controls();
SplitBoundaryReport
run_nominal_hydro_directed_scratch_phase_timing_controls();
SplitBoundaryReport
run_nominal_hydro_directed_scratch_setup_timing_controls();
SplitBoundaryReport
run_nominal_hydro_directed_scratch_cpu_timing_controls();
SplitBoundaryReport
run_nominal_hydro_directed_scratch_evaluation_buffer_audit_controls();
SplitBoundaryReport
run_nominal_hydro_topology_incoming_fusion_audit_controls();
SplitBoundaryReport run_nominal_dam_first_output_controls();
SplitBoundaryReport run_nominal_dam_reference_first_output_controls();
SplitBoundaryReport run_nominal_dam_step2_strain_refinement_controls();
SplitBoundaryReport run_pressure_state_formulation_controls();
SplitBoundaryReport run_al_path_oracle_controls();
SplitBoundaryReport run_al_dense_vector_oracle_controls();
SplitBoundaryReport run_al_dense_vector_stable_commit_controls();
SplitBoundaryReport run_al_inner_floor_diagnostic_controls();
SplitBoundaryReport run_al_topology_step_discriminator_controls();
SplitBoundaryReport run_al_topology_step_signed_zero_reclosure_controls();
SplitBoundaryReport run_al_globalization_policy_discriminator_controls();
SplitBoundaryReport run_al_step_norm_trust_inner_controls();
SplitBoundaryReport run_al_step_norm_private_outer_controls();
SplitBoundaryReport run_al_cap_accuracy_discriminator_controls();
SplitBoundaryReport run_al_inner_floor_mechanism_discriminator_controls();
SplitBoundaryReport run_al_extended_precision_energy_discriminator_controls();
SplitBoundaryReport run_al_divided_difference_discriminator_controls();
SplitBoundaryReport run_al_divided_difference_reclosure_controls();
SplitBoundaryReport run_al_divided_difference_private_inner_controls();
SplitBoundaryReport run_al_binary128_accepted_sign_oracle_controls();
SplitBoundaryReport run_al_divided_private_outer_continuation_controls();
SplitBoundaryReport run_al_divided_full_private_transaction_controls();
SplitBoundaryReport run_al_sparse_workspace_equivalence_controls();
SplitBoundaryReport run_al_nominal_prerequisites_controls();
SplitBoundaryReport run_al_sparse_precision_transaction_controls();
SplitBoundaryReport run_al_nominal_substep_shadow_controls();
SplitBoundaryReport run_al_kappa_scaling_prerequisites_controls();
SplitBoundaryReport run_al_nondimensional_transaction_controls();
SplitBoundaryReport run_al_full_normalized_private_transaction_controls();
SplitBoundaryReport
run_al_normalized_divided_precancellation_replay_controls();
SplitBoundaryReport
run_al_full_normalized_precancelled_private_transaction_controls();
SplitBoundaryReport
run_al_normalized_krylov_forcing_replay_controls();
SplitBoundaryReport
run_al_full_normalized_dimensionless_forcing_private_transaction_controls();
SplitBoundaryReport
run_al_normalized_nominal_substep_shadow_controls();
SplitBoundaryReport
run_al_topology_precision_shell_replay_controls();
SplitBoundaryReport
run_al_binary64_topology_nominal_substep_shadow_controls();
SplitBoundaryReport
run_al_sixth_trust_recurrence_replay_controls();
SplitBoundaryReport
run_al_krylov_model_image_discriminator_controls();
SplitBoundaryReport
run_al_guarded_sixth_trial_shadow_controls();
SplitBoundaryReport
run_al_guarded_residual_private_transaction_controls();
SplitBoundaryReport run_al_second_guard_boundary_replay_controls();
SplitBoundaryReport
run_al_tiered_grace_model_image_discriminator_controls();
SplitBoundaryReport run_al_tiered_grace_private_transaction_controls();
SplitBoundaryReport run_al_total_hvp_boundary_diagnostic_controls();
SplitBoundaryReport run_al_total_budget_offline_replay_controls();
SplitBoundaryReport run_al_total_budget_atomic_completion_controls();
SplitBoundaryReport run_al_post_acceptance_boundary_controls();
SplitBoundaryReport run_al_soft_cap_suspension_projection_controls();
SplitBoundaryReport run_al_token_completeness_controls();
SplitBoundaryReport run_al_v2_envelope_validation_controls();
SplitBoundaryReport run_al_owner_epoch_transition_controls();
SplitBoundaryReport run_al_shadow_outer6_resume_controls();
SplitBoundaryReport run_al_within_epoch_outer7_grant_controls();
SplitBoundaryReport run_al_shadow_outer7_execution_controls();
SplitBoundaryReport run_al_within_epoch_outer8_grant_controls();
SplitBoundaryReport run_al_shadow_outer8_execution_controls();
SplitBoundaryReport run_al_within_epoch_outer9_grant_controls();
SplitBoundaryReport run_al_shadow_outer9_execution_controls();
SplitBoundaryReport run_al_within_epoch_outer10_grant_controls();
SplitBoundaryReport run_al_shadow_outer10_execution_controls();
SplitBoundaryReport run_al_within_epoch_outer11_grant_controls();
SplitBoundaryReport run_al_shadow_outer11_execution_controls();
SplitBoundaryReport run_al_linearized_feasibility_operator_controls();
SplitBoundaryReport run_al_linearized_range_projection_controls();
SplitBoundaryReport run_al_scalar_feasibility_interval_controls();
SplitBoundaryReport run_al_all_inequality_cauchy_step_controls();
SplitBoundaryReport run_al_iterated_all_inequality_normal_step_controls();
SplitBoundaryReport run_al_first_order_reference_extension_controls();
SplitBoundaryReport run_al_equal_work_generalized_hessian_controls();
SplitBoundaryReport run_al_equal_work_curvature_polish_hybrid_controls();
SplitBoundaryReport run_al_hybrid_polish_continuation_controls();
SplitBoundaryReport run_al_direction_memory_replay_controls();
SplitBoundaryReport run_al_guarded_hz_recurrence_controls();
SplitBoundaryReport run_al_nonlinear_normal_acceptance_controls();
SplitBoundaryReport run_al_support_crossing_contact_audit_controls();
SplitBoundaryReport run_al_stable_superset_relinearization_controls();
SplitBoundaryReport run_al_contact_tangent_normal_step_controls();
SplitBoundaryReport run_al_contact_feasible_common_descent_controls();
SplitBoundaryReport run_al_nonlinear_line_globalization_controls();
SplitBoundaryReport run_al_filter_globalization_controls();
SplitBoundaryReport run_al_filter_compatibility_controls();
SplitBoundaryReport run_al_restoration_certificate_controls();
SplitBoundaryReport run_al_restoration_hz_accelerator_controls();
SplitBoundaryReport run_al_active_face_closure_controls();
SplitBoundaryReport run_al_persistent_master_controls();
SplitBoundaryReport run_al_persistent_master_sweep_depth_controls();
SplitBoundaryReport run_al_operator_consistency_decomposition_controls();
SplitBoundaryReport run_al_model_projection_decomposition_controls();
SplitBoundaryReport run_al_contact_constrained_dykstra_controls();
SplitBoundaryReport run_al_joint_witness_certificate_controls();
SplitBoundaryReport run_al_certificate_aware_refinement_controls();
SplitBoundaryReport run_al_directed_enclosure_fixed_point_controls();
SplitBoundaryReport run_al_row_local_enclosure_controls();
SplitBoundaryReport run_al_certificate_validation_controls();
SplitBoundaryReport run_al_certificate_integration_controls();
SplitBoundaryReport run_al_restoration_exit_transaction_controls();
SplitBoundaryReport run_al_cached_normal_projection_trqp_controls();
SplitBoundaryReport run_al_sparse_row_operator_controls();
SplitBoundaryReport run_al_dynamic_all_row_probe_controls();
SplitBoundaryReport run_al_active_face_fista_probe_controls();
SplitBoundaryReport run_al_active_face_pcg_probe_controls();
SplitBoundaryReport run_al_best_composed_dual_path_controls();
SplitBoundaryReport run_al_equal_work_dual_completion_controls();
SplitBoundaryReport run_al_generalization_corpus_manifest_controls();
SplitBoundaryReport run_al_generalization_operator_preflight_controls();
SplitBoundaryReport run_al_generalization_binary128_oracle_controls();
SplitBoundaryReport run_al_generalization_admm_oracle_controls();
SplitBoundaryReport run_al_generalization_mpadmm_oracle_controls();
SplitBoundaryReport run_al_generalization_projector_derivative_controls();
SplitBoundaryReport run_al_generalization_newton_direction_controls();
SplitBoundaryReport run_al_generalization_nnqp_representative_controls();
SplitBoundaryReport run_al_generalization_iterative_semismooth_controls();
SplitBoundaryReport run_al_generalization_verified_inverse_controls();
SplitBoundaryReport run_al_generalization_v3_manifest_controls();
SplitBoundaryReport run_al_generalization_v3_preflight_controls();
SplitBoundaryReport run_al_generalization_v3_solver_controls();
SplitBoundaryReport run_al_generalization_v3_failure_diagnostic_controls();
SplitBoundaryReport run_al_generalization_v3_ratio_diagnostic_controls();
SplitBoundaryReport run_al_generalization_v3_ratio_error_budget_controls();
SplitBoundaryReport run_al_generalization_v3_affine_shadow_controls();
SplitBoundaryReport run_al_generalization_v3_current_provenance_controls();
SplitBoundaryReport
run_al_generalization_v3_dual_refinement_candidate_controls();
SplitBoundaryReport run_al_generalization_v3_shear_trajectory_controls();
SplitBoundaryReport run_al_generalization_v3_line_frontier_controls();
SplitBoundaryReport run_al_generalization_v3_breakpoint_geometry_controls();
SplitBoundaryReport run_al_generalization_v3_fixed_face_event_controls();
SplitBoundaryReport run_al_generalization_v3_event_side_trial_controls();
SplitBoundaryReport run_al_generalization_v3_ulp_ladder_controls();
SplitBoundaryReport run_al_generalization_v3_zero_bound_flutter_controls();
SplitBoundaryReport run_al_generalization_v3_event_forward_bound_controls();
SplitBoundaryReport run_al_generalization_v3_certified_event_trajectory_controls();
SplitBoundaryReport
run_al_generalization_v3_post_event_globalization_controls();
SplitBoundaryReport run_al_generalization_v3_sub_envelope_event_controls();
SplitBoundaryReport
run_al_generalization_v3_exhausted_line_recovery_controls();
SplitBoundaryReport
run_al_generalization_v3_post_recovery_globalization_controls();
SplitBoundaryReport run_al_generalization_v3_terminal_certificate_controls();
SplitBoundaryReport run_al_generalization_v3_terminal_trajectory_controls();
SplitBoundaryReport run_al_generalization_v4_manifest_controls();
SplitBoundaryReport run_al_generalization_v4_preflight_controls();
SplitBoundaryReport run_al_generalization_v4_solver_controls();
SplitBoundaryReport run_al_generalization_v4_failure_budget_controls();
SplitBoundaryReport run_al_generalization_v4_exact_inverse_residual_controls();
SplitBoundaryReport run_al_generalization_v4_dot2_inverse_certificate_controls();
SplitBoundaryReport run_al_generalization_v4_dot2_solution_error_controls();
SplitBoundaryReport run_al_generalization_v4_directional_krawczyk_controls();
SplitBoundaryReport run_al_generalization_v4_centered_neumann_controls();
SplitBoundaryReport run_al_generalization_v4_centered_refinement_trajectory_controls();
SplitBoundaryReport run_al_generalization_v4_depth8_ratio_trajectory_controls();
SplitBoundaryReport run_al_generalization_v4_second_inverse_contraction_controls();
SplitBoundaryReport run_al_generalization_v4_second_centered_solution_controls();
SplitBoundaryReport run_al_generalization_v4_two_refinement_trajectory_controls();
SplitBoundaryReport run_al_generalization_v4_third_inverse_contraction_controls();
SplitBoundaryReport run_al_generalization_v4_third_centered_solution_controls();
SplitBoundaryReport run_al_generalization_v4_three_refinement_trajectory_controls();
SplitBoundaryReport run_al_generalization_v4_generic_centered_verifier_controls();
SplitBoundaryReport run_al_generalization_v4_generic_corpus_controls();
SplitBoundaryReport run_al_generalization_v4_counterflow_centered_slope_controls();
SplitBoundaryReport run_al_generalization_v4_counterflow_direct_center_controls();
SplitBoundaryReport run_al_generalization_v4_counterflow_legacy_slope_controls();
SplitBoundaryReport run_al_generalization_v4_counterflow_slope_trajectory_controls();
SplitBoundaryReport run_al_generalization_v4_composed_corpus_controls();
SplitBoundaryReport run_al_generalization_v5_manifest_controls();
SplitBoundaryReport run_al_generalization_v5_preflight_controls();
SplitBoundaryReport run_al_generalization_v5_blind_replay_controls();
SplitBoundaryReport run_al_generalization_v5_dimension_generic_center_controls();
SplitBoundaryReport run_al_generalization_v5_profile_bounded_callback_controls();
SplitBoundaryReport run_al_generalization_v5_binary64_dot2err_controls();
SplitBoundaryReport run_al_generalization_v5_projection_conditioning_controls();
SplitBoundaryReport run_al_generalization_v5_factor_space_controls();
SplitBoundaryReport run_al_generalization_v5_orientation_matched_factor_controls();
SplitBoundaryReport run_al_generalization_v5_active_row_rank_controls();
SplitBoundaryReport run_al_generalization_v5_projector_nullspace_controls();
SplitBoundaryReport
run_al_generalization_v5_representative_injectivity_controls();
SplitBoundaryReport
run_al_generalization_v5_rectangular_factor_precision_controls();
SplitBoundaryReport
run_al_generalization_v5_bounded_wide_factor_controls();
SplitBoundaryReport
run_al_generalization_v5_exported_factor_rhs_controls();
SplitBoundaryReport
run_al_generalization_v5_original_residual_refinement_controls();
SplitBoundaryReport
run_al_generalization_v5_factor_standard_refinement_controls();
SplitBoundaryReport
run_al_generalization_v5_wide_refinement_frontier_controls();
SplitBoundaryReport
run_al_generalization_v5_preconditioned_cg_controls();
SplitBoundaryReport
run_al_generalization_v5_matrix_free_correspondence_controls();
SplitBoundaryReport
run_al_generalization_v5_canonical_defect_transport_controls();
SplitBoundaryReport
run_al_generalization_v5_projector_idempotence_controls();
SplitBoundaryReport
run_al_generalization_v5_full_operator_materialization_controls();
SplitBoundaryReport
run_al_generalization_v5_common_operator_inverse_controls();
SplitBoundaryReport
run_al_generalization_v5_common_operator_pcg_controls();
SplitBoundaryReport
run_al_generalization_v5_common_residual_recoverability_controls();
SplitBoundaryReport run_nominal_dam_first_output_preflight_controls();
SplitBoundaryReport run_nominal_dam_reference_binary64_topology_controls();

} // namespace nextengine::nonlocal::fcr
