[package]
name = "next_verification"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
desktop-sdl-ash = ["dep:next_desktop_sdl_ash"]
physx = ["dep:next_physics_physx", "next_runtime/physx"]
physx-mock = ["dep:next_physics_physx", "next_runtime/physx-mock"]

[dependencies]
next_agent.workspace = true
next_application.workspace = true
next_assets.workspace = true
next_cli.workspace = true
next_contracts.workspace = true
next_motor.workspace = true
next_desktop_sdl_ash = { workspace = true, optional = true }
next_physics_api.workspace = true
next_physics_physx = { workspace = true, optional = true }
next_platform.workspace = true
next_plugin_host.workspace = true
next_presentation.workspace = true
next_project.workspace = true
next_reference_game.workspace = true
next_render.workspace = true
next_runtime.workspace = true
next_script_luau.workspace = true
next_world.workspace = true
serde_json.workspace = true

[lints]
workspace = true
