[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
default-run = "xtask"

[features]
default = []
desktop-sdl-ash = ["next_verification/desktop-sdl-ash"]
physx = ["next_verification/physx"]
physx-mock = ["next_verification/physx-mock"]

[dependencies]
goblin.workspace = true
next_assets.workspace = true
next_application.workspace = true
next_contracts.workspace = true
next_process_allocation_counter.workspace = true
next_project.workspace = true
next_reference_game.workspace = true
next_verification.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[build-dependencies]
sha2.workspace = true

[lints]
workspace = true
