[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
default-run = "xtask"

[features]
default = []
desktop-sdl-ash = ["next_verification/desktop-sdl-ash"]
physx = ["next_motor/physx-sdk", "next_verification/physx"]
physx-mock = ["next_motor/mock-abi", "next_verification/physx-mock"]

[dependencies]
crc32fast.workspace = true
flate2.workspace = true
goblin.workspace = true
next_assets.workspace = true
next_application.workspace = true
next_cli.workspace = true
next_contracts.workspace = true
next_continuum_water.workspace = true
next_motor.workspace = true
next_project.workspace = true
next_presentation.workspace = true
next_reference_game.workspace = true
next_render.workspace = true
next_verification.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
zip.workspace = true

[build-dependencies]
sha2.workspace = true

[lints]
workspace = true
