[package]
name = "next_application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
next_assets.workspace = true
next_contracts.workspace = true
next_project.workspace = true
next_presentation.workspace = true
next_reference_game.workspace = true
next_runtime.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
